/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-105883-g3706fb8f16-20220308"
#endif /* AVUTIL_FFVERSION_H */
